// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_web.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyAjPhATGyTJlugfHjzRSi6wTtRtps1uFLc',
      appId: '1:1090542890690:android:17c81a20e0b1596e7e155b',
      messagingSenderId: '1090542890690',
      projectId: 'beh-doctor',
      storageBucket: 'beh-doctor.firebasestorage.app',
    );
  }
}
